
ssh-add -A

alias c="clear"
alias vim='nvim'
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# MacPorts Installer addition on 2015-01-29_at_14:59:07: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

#if [ -e /usr/share/terminfo/78/xterm-256color ]; then
#    export TERM='xterm-256color'
#else
#    export TERM='xterm-color'
#fi

. "$(brew --prefix nvm)/nvm.sh"
#. "/usr/local/opt/nvm/nvm.sh"
export EDITOR="nvim"
export SHELL="zsh"
alias docker-rm-stopped="docker rm $(docker ps -a -q)"
alias wind='tmux new-window \; split-window -h -l 108 \; split-window -v'
alias panes='tmux split-window -h \; split-window -v'
export XDG_RUNTIME_DIR="/tmp"
